### ISSUE TITLE
How can I apply for solana interns?

### ISSUE THREAD

**Issue by cynic-1** [solana-labs/interns-codehub#1]
Hey guys, I really want to learn some things about solana. How can I apply for solana interns? Or is  there any chance that I can contribute to solana-labs' open source projects? I just need someone to get me on the road.

**Comment by drestark** [comment]
you have to start with rust and you can check out there website for open position

**Comment by cynic-1** [comment]
You are right. I just look forward to having the luck to have guys from solana labs to tell me about detail since the repo name is interns-codehub.^^

**Comment by drestark** [comment]
hit them up on twitter, they often respond their faster
